<a href="https://colab.research.google.com/github/Anushka-coder1/reccomend_book/blob/main/book_recommend.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
ratings = pd.read_csv('/content/Ratings.csv')
users = pd.read_csv('/content/Users.csv')

In [ ]:
books = pd.read_csv('/content/Books.csv')
books.head(1)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002.0,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...

In [ ]:
ratings.head()
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1119204 entries, 0 to 1119203
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   User-ID      1119204 non-null  int64
 1   ISBN         1119204 non-null  object
 2   Book-Rating  1119203 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 25.6+ MB

In [ ]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [ ]:
print(Books.shape)
print(ratings.shape)
print(users.shape)

(271360, 8)
(1119204, 3)
(278858, 3)

In [ ]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  object
 1   Book-Title           271360 non-null  object
 2   Book-Author          271358 non-null  object
 3   Year-Of-Publication  271360 non-null  object
 4   Publisher            271358 non-null  object
 5   Image-URL-S          271360 non-null  object
 6   Image-URL-M          271360 non-null  object
 7   Image-URL-L          271357 non-null  object
dtypes: object(8)
memory usage: 16.6+ MB

In [ ]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [ ]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    1
dtype: int64

In [ ]:
users.duplicated().sum()
books.duplicated().sum()
ratings.duplicated().sum()

np.int64(0)

# Perform EDA

# Popularity based Recommendation System

In [ ]:
# merging ratings and books

In [ ]:
ratings_with_name = ratings.merge(books,on='ISBN')
ratings_with_name.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1003949 entries, 0 to 1003948
Data columns (total 10 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   User-ID              1003949 non-null  int64
 1   ISBN                 1003949 non-null  object
 2   Book-Rating          1003949 non-null  float64
 3   Book-Title           1003949 non-null  object
 4   Book-Author          1003947 non-null  object
 5   Year-Of-Publication  1003949 non-null  object
 6   Publisher            1003947 non-null  object
 7   Image-URL-S          1003949 non-null  object
 8   Image-URL-M          1003949 non-null  object
 9   Image-URL-L          1003945 non-null  object
dtypes: float64(1), int64(1), object(8)
memory usage: 76.6+ MB

In [ ]:
num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns = {'Book-Rating' : 'num-ratings'} , inplace=True)
num_rating_df

In [ ]:
avg_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
avg_rating_df.rename(columns = {'Book-Rating' : 'avg-ratings'} , inplace=True)
avg_rating_df

TypeError: agg function failed [how->mean,dtype->object]